// Generated code

#if !DEBUG
#include "Shaders/ShaderProvider/ShaderProvider.h"
const string ShaderProvider::UnpackCode(const uint32_t& h) {
switch (h) {
case 1939412094: return "#version 460 core\nin vec2 fragmentTextureCoords;uniform sampler2D dataTexture;out vec4 color;void main(){color=texture(dataTexture,fragmentTextureCoords);}";
case 776390504: return "#version 460 core\nin vec4 position;in vec2 vertexTextureCoords;out vec2 fragmentTextureCoords;void main(){gl_Position=position;fragmentTextureCoords=vertexTextureCoords;}";
case 4198337046: return "#version 460 core\nlayout(local_size_x=8,local_size_y=8,local_size_z=1)in;uniform ivec2 size;uniform dvec2 scale;uniform dvec2 pan;uniform float lightHeight;uniform vec2 lightDirection;uniform float oddIterationsTint;uniform float evenIterationsTint;uniform uint maxIterations;uniform dvec2 constant;layout(rgba32f)restrict uniform image2D dataTexture;dvec2 a(ivec2 k){dvec2 l=size*scale;dvec2 m=k/l;dvec2 n=m+pan;return(n*4)-(2/scale);}dvec2 c(dvec2 o,dvec2 p){return dvec2((o.x*p.x)-(o.y*p.y),(o.x*p.y)+(o.y*p.x));}dvec2 d(dvec2 q,dvec2 s){double t=(s.x*s.x)+(s.y*s.y);return dvec2(((q.x*s.x)+(q.y*s.y))/t,((q.y*s.x)-(q.x*s.y))/t);}void e(dvec2 u,inout uint v,out float w){dvec2 z=u;dvec2 A=dvec2(1,0);while(dot(z,z)<650&&v<maxIterations){A=c(A*2,z)+dvec2(1,0);z=c(z,z)+constant;v++;}dvec2 B=d(z,A);w=float(dot(normalize(B),lightDirection)+lightHeight);w=max(0,w/(1+lightHeight));}vec3 f(float i){float r=9*(1-i)*i*i*i;float g=15*(1-i)*(1-i)*i*i;float b=8.5*(1-i)*(1-i)*(1-i)*i;return vec3(r,g,b);}void h(inout vec3 C,uint D,float E){uint F=D%2;C+=C*F*E;}void j(inout vec3 G,float H){G=clamp(G,vec3(0),vec3(1));G*=H;}void main(){ivec2 I=ivec2(gl_GlobalInvocationID.xy);if(I.x>=size.x||I.y>=size.y)return;float J;uint K=0;dvec2 L=a(I);e(L,K,J);float M=K/float(maxIterations);vec3 N=f(M);h(N,K,oddIterationsTint);h(N,K+1,evenIterationsTint);j(N,J);imageStore(dataTexture,I,vec4(N,1));}";
case 1519105128: return "#version 460 core\nlayout(local_size_x=8,local_size_y=8,local_size_z=1)in;uniform ivec2 size;uniform dvec2 scale;uniform dvec2 pan;uniform uint maxIterations;uniform dvec2 constant;layout(rgba32f)restrict uniform image2D dataTexture;dvec2 a(ivec2 e){dvec2 f=size*scale;dvec2 h=e/f;dvec2 j=h+pan;return(j*4)-(2/scale);}int c(dvec2 k){int l=0;dvec2 m=k;while(dot(m,m)<4&&l<maxIterations){l++;m=constant+dvec2((m.x*m.x)-(m.y*m.y),2*m.x*m.y);}return l;}vec4 d(float i){float r=9*(1-i)*i*i*i;float g=15*(1-i)*(1-i)*i*i;float b=8.5*(1-i)*(1-i)*(1-i)*i;return vec4(r,g,b,1);}void main(){ivec2 n=ivec2(gl_GlobalInvocationID.xy);if(n.x>=size.x||n.y>=size.y)return;dvec2 o=a(n);int p=c(o);float q=p/float(maxIterations);imageStore(dataTexture,n,d(q));}";
case 214932553: return "#version 460 core\nlayout(local_size_x=8,local_size_y=8,local_size_z=1)in;uniform ivec2 size;uniform dvec2 scale;uniform dvec2 pan;uniform float lightHeight;uniform vec2 lightDirection;uniform float oddIterationsTint;uniform float evenIterationsTint;uniform uint maxIterations;layout(rgba32f)restrict uniform image2D dataTexture;dvec2 a(ivec2 l){dvec2 m=size*scale;dvec2 n=l/m;dvec2 o=n+pan;return(o*4)-(2/scale);}dvec2 c(dvec2 p){return dvec2(p.x,-p.y);}dvec2 d(dvec2 q,dvec2 s){return dvec2((q.x*s.x)-(q.y*s.y),(q.x*s.y)+(q.y*s.x));}dvec2 e(dvec2 t){double u=dot(t,t);float v=atan(float(t.y),float(t.x));return dvec2(u*cos(2*v),u*sin(2*v));}void f(dvec2 w,inout uint z,out float A){dvec2 B=w;dvec2 C=dvec2(0,0);dvec2 D=dvec2(1,0);while(dot(B,B)<650&&z<maxIterations){C=2*(d(C,B)+e(D));D=d(D*2,B)+dvec2(1,0);B=d(B,B)+w;z++;}float E=.5*log(float(dot(B,B)));dvec2 F=d(d(B,D),((E+1)*c(e(D)))-(E*c(d(B,C))));A=float(dot(normalize(F),lightDirection)+lightHeight);A=max(0,A/(1+lightHeight));}vec3 h(float i){float r=9*(1-i)*i*i*i;float g=15*(1-i)*(1-i)*i*i;float b=8.5*(1-i)*(1-i)*(1-i)*i;return vec3(r,g,b);}void j(inout vec3 G,uint H,float I){uint J=H%2;G+=G*J*I;}void k(inout vec3 K,float L){K=clamp(K,vec3(0),vec3(1));K*=L;}void main(){ivec2 M=ivec2(gl_GlobalInvocationID.xy);if(M.x>=size.x||M.y>=size.y)return;float N;uint O=0;dvec2 P=a(M);f(P,O,N);float Q=O/float(maxIterations);vec3 R=h(Q);j(R,O,oddIterationsTint);j(R,O+1,evenIterationsTint);k(R,N);imageStore(dataTexture,M,vec4(R,1));}";
case 3229525275: return "#version 460 core\nlayout(local_size_x=8,local_size_y=8,local_size_z=1)in;uniform ivec2 size;uniform dvec2 scale;uniform dvec2 pan;uniform uint maxIterations;layout(rgba32f)restrict uniform image2D dataTexture;dvec2 a(ivec2 e){dvec2 f=size*scale;dvec2 h=e/f;dvec2 j=h+pan;return(j*4)-(2/scale);}int c(dvec2 k){int i=0;double x=0;double y=0;double l=0;double m=0;while(l+m<4&&i<maxIterations){y=2*x*y+k.y;x=l-m+k.x;l=x*x;m=y*y;i++;}return i;}vec4 d(float i){float r=9*(1-i)*i*i*i;float g=15*(1-i)*(1-i)*i*i;float b=8.5*(1-i)*(1-i)*(1-i)*i;return vec4(r,g,b,1);}void main(){ivec2 n=ivec2(gl_GlobalInvocationID.xy);if(n.x>=size.x||n.y>=size.y)return;dvec2 o=a(n);int p=c(o);float q=p/float(maxIterations);imageStore(dataTexture,n,d(q));}";
default: return ""; }}
#endif
